import { library } from "@fortawesome/fontawesome-svg-core";
import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
import {
  faSeedling,
  faPenToSquare,
  faChartLine,
  faGear,
  faMoon,
  faSun,
  faCloudSun,
  faCloud,
  faCircle,
  faCheck,
  faArrowLeft,
  faRightFromBracket,
  faPlus,
  faTrash,
  faClock,
  faEnvelope,
  faLock,
  faUser,
  faDroplet,
  faTriangleExclamation,
  faBolt,
  faHeart,
  faBatteryFull,
  faBatteryHalf,
  faBatteryQuarter,
  faBatteryEmpty,
  faLeaf,
  faCalendarDay,
  faFire,
  faSpinner,
  faArrowRight,
} from "@fortawesome/free-solid-svg-icons";
import {
  faFaceSmile,
  faFaceMeh,
  faFaceFrown,
  faFaceTired,
} from "@fortawesome/free-regular-svg-icons";

// Prevent Font Awesome from adding its CSS automatically (we import it above)
config.autoAddCss = false;

library.add(
  faSeedling,
  faPenToSquare,
  faChartLine,
  faGear,
  faMoon,
  faSun,
  faCloudSun,
  faCloud,
  faCircle,
  faCheck,
  faArrowLeft,
  faRightFromBracket,
  faPlus,
  faTrash,
  faClock,
  faEnvelope,
  faLock,
  faUser,
  faDroplet,
  faTriangleExclamation,
  faBolt,
  faHeart,
  faBatteryFull,
  faBatteryHalf,
  faBatteryQuarter,
  faBatteryEmpty,
  faLeaf,
  faCalendarDay,
  faFire,
  faSpinner,
  faArrowRight,
  faFaceSmile,
  faFaceMeh,
  faFaceFrown,
  faFaceTired
);
